apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management-observability
---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: REPLACE_WITH_BUCKET_NAME
      endpoint: s3.REPLACE_WITH_REGION.amazonaws.com
      access_key: REPLACE_WITH_ACCESS_KEY
      secret_key: REPLACE_WITH_SECRET_KEY
