apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhacm-install
  namespace: openshift-gitops
spec:
  destination:
    namespace: open-cluster-management
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: false
    path: rhacm
    repoURL: https://github.com/andyrepton/rosa-demos
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
