apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: bgp-demo-network
  labels:
    advertise: "true"
spec:
  namespaceSelector:
    matchLabels:
      cluster-udn: bgp-demo-network
  network:
    topology: Layer2
    layer2:
      role: Primary
      subnets:
        - "10.100.0.0/16"
