apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  serviceAccount:
    name: logcollector
  outputs:
    - name: cw
      type: cloudwatch
      cloudwatch:
        groupName: 'poc-andyr.{.log_type||"unknown"}'
        region: eu-west-2
        authentication:
          type: iamRole
          iamRole:
            roleARN:
              secretName: cloudwatch-role
              key: role_arn
            token:
              from: serviceAccount
  pipelines:
    - name: to-cloudwatch
      inputRefs:
        - infrastructure
        - audit
      outputRefs:
        - cw
