apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: workstation-cluster-b
  namespace: industrial-spoke
spec:
  running: true
  template:
    spec:
      nodeSelector:
        industrial-role: spoke
      domain:
        devices:
          interfaces:
            - name: default
              masquerade: {}
            - name: industrial-net
              bridge: {}
        resources:
          requests:
            memory: 2Gi
            cpu: 1
      networks:
        - name: default
          pod: {}
        - name: industrial-net
          multus:
            networkName: industrial-bridge-network
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:latest
        - name: cloudinit
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
              write_files:
                - path: /etc/NetworkManager/system-connections/industrial.nmconnection
                  permissions: '0600'
                  content: |
                    [connection]
                    id=industrial
                    type=ethernet
                    interface-name=enp2s0
                    [ipv4]
                    method=manual
                    addresses=192.168.100.52/24
                    [ipv6]
                    method=disabled
              runcmd:
                - nmcli con reload
                - nmcli con up industrial
