apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: vllm-runtime
  namespace: vllm-model-serving
  annotations:
    opendatahub.io/template-display-name: vLLM Runtime
spec:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/path: /metrics
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  containers:
    - name: kserve-container
      image: registry.redhat.io/rhaii/vllm-cuda-rhel9:3.5.0
      ports:
        - containerPort: 8000
          protocol: TCP
      command:
        - python
        - -m
        - vllm.entrypoints.openai.api_server
      env:
        - name: HF_HUB_OFFLINE
          value: "1"
      resources:
        requests:
          cpu: "4"
          memory: 32Gi
          nvidia.com/gpu: "1"
        limits:
          cpu: "8"
          memory: 48Gi
          nvidia.com/gpu: "1"
