apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: granite-4-1-30b
  namespace: claude-code-demo
spec:
  modelRef:
    kind: LLMInferenceService
    name: granite-4-1-30b
---
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: qwen3-6-27b
  namespace: claude-code-demo
spec:
  modelRef:
    kind: LLMInferenceService
    name: qwen3-6-27b
