apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  annotations:
    cdi.kubevirt.io/minimumSupportedPvcSize: 4Gi
  name: hyperdisk
spec:
  claimPropertySets:
    - accessModes:
        - ReadWriteOnce
      volumeMode: Block
    - accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
