apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-6-27b-model-storage
  namespace: claude-code-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
