# Use the official Fedora image as the base image
FROM fedora:latest

# Install OpenLDAP
RUN dnf install -y openldap-servers openldap-clients && \
    dnf clean all

# Expose the LDAP port
EXPOSE 389

COPY slapd.conf /etc/openldap/slapd.conf

# Add test data (Optional)
COPY ldap.conf /etc/openldap/ldap.conf

COPY testdata.ldif /root/testdata.ldif
RUN slapadd -l /root/testdata.ldif

# Start the LDAP server
CMD ["slapd", "-d", "0", "-h", "ldap:///"]

