apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: industrial-l2-network
  namespace: industrial-vms
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "br-industrial"
    }'
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: windows-industrial-controller
  namespace: industrial-vms
spec:
  domain:
    devices:
      interfaces:
        - name: default
          masquerade: {}
        - name: factory-nic
          bridge: {} # Bridges the VM into the node's br-industrial
  networks:
    - name: default
      pod: {}
    - name: factory-nic
      multus:
        networkName: industrial-l2-network # Must match the NAD name
