apiVersion: v1
kind: Secret
metadata:
  name: factory-vpn-config
  namespace: industrial-network
type: Opaque
stringData:
  client.conf: |
    client
    dev tap
    proto udp
    # Point to the simulator service in the other namespace
    remote vpn-server-svc.factory-simulator.svc.cluster.local 1194
    resolv-retry infinite
    nobind
    persist-key
    persist-tun
    
    # Updated paths for sub-directory mounting
    ca /etc/openvpn/certs/ca.crt
    cert /etc/openvpn/certs/client.crt
    key /etc/openvpn/certs/client.key
    
    #remote-cert-tls server
    cipher AES-256-GCM
    verb 3
    
    # Writeable status path
    status /tmp/openvpn-status.log
