apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mtv-cclm-binding
subjects:
- kind: ServiceAccount
  name: mtv-cclm
  namespace: openshift-mtv
roleRef:
  kind: ClusterRole
  name: mtv-cclm-role
  apiGroup: rbac.authorization.k8s.io
