apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-mesh-install
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: false
    path: openshift-service-mesh
    repoURL: https://github.com/andyrepton/managed-openshift-demos
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
