apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: collector
  namespace: openshift-logging
spec:
  collector:
    resources:
      limits:
        memory: 4Gi
      requests:
        memory: 256Mi
  serviceAccount:
    name: collector
  filters:
    - name: add-cluster-label
      type: openshiftLabels
      openshiftLabels:
        cluster: onprem
  outputs:
    - name: rosa-loki-application
      type: loki
      loki:
        url: "https://loki-gateway.REPLACE_WITH_ROSA_DOMAIN/api/logs/v1/application"
        authentication:
          token:
            from: secret
            secret:
              name: loki-rosa-bearer-token
              key: token
      tls:
        securityProfile:
          type: Intermediate
    - name: rosa-loki-infrastructure
      type: loki
      loki:
        url: "https://loki-gateway.REPLACE_WITH_ROSA_DOMAIN/api/logs/v1/infrastructure"
        authentication:
          token:
            from: secret
            secret:
              name: loki-rosa-bearer-token
              key: token
      tls:
        securityProfile:
          type: Intermediate
  pipelines:
    - name: application-logs-to-rosa
      inputRefs:
        - application
      outputRefs:
        - rosa-loki-application
      filterRefs:
        - add-cluster-label
    - name: infrastructure-logs-to-rosa
      inputRefs:
        - infrastructure
      outputRefs:
        - rosa-loki-infrastructure
      filterRefs:
        - add-cluster-label
