apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vllm-granite-gateway
  namespace: claude-code-demo
  labels:
    app: vllm-gateway
  annotations:
    haproxy.router.openshift.io/timeout: 10m
spec:
  to:
    kind: Service
    name: granite-4-1-30b-predictor
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vllm-qwen-gateway
  namespace: claude-code-demo
  labels:
    app: vllm-gateway
  annotations:
    haproxy.router.openshift.io/timeout: 10m
spec:
  to:
    kind: Service
    name: qwen3-6-27b-predictor
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
