apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-logging-operator
  namespace: open-cluster-management
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: logging-namespace
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-logging
                  annotations:
                    openshift.io/node-selector: ""
                  labels:
                    openshift.io/cluster-monitoring: "true"
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: logging-operator-group
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: cluster-logging
                  namespace: openshift-logging
                spec:
                  targetNamespaces:
                    - openshift-logging
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: logging-operator-subscription
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: cluster-logging
                  namespace: openshift-logging
                spec:
                  channel: "stable-6.6"
                  name: cluster-logging
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
