apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-no-privileged-pods
  namespace: open-cluster-management
  annotations:
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-7 Boundary Protection
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: no-privileged-containers
        spec:
          remediationAction: inform
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
              - open-cluster-management*
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  namespace: "{{ .metadata.namespace }}"
                spec:
                  containers:
                    - securityContext:
                        privileged: true
